#!/usr/bin/env python3
"""Regenerate public/textures/CREDITS.md and public/models/props/CREDITS.md from the manifests
(materials.json, glass/interiors.json, env/env.json, props.json). Run after any rebuild.
"""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
TEX = os.path.join(ROOT, 'public', 'textures')
PROPS = os.path.join(ROOT, 'public', 'models', 'props')


def textures():
    man = json.load(open(os.path.join(TEX, 'materials.json')))
    env = json.load(open(os.path.join(TEX, 'env', 'env.json')))
    L = ['# Texture credits', '',
         'Every file in `public/textures/` is **CC0 1.0 (public domain dedication)**: no attribution is legally '
         'required, but we credit the authors anyway. Sources were downloaded through the official APIs '
         '(ambientCG `api/v2/full_json`, Poly Haven `api.polyhaven.com`) and converted by `tools/materials/`.', '',
         '- ambientCG: <https://ambientcg.com> — CC0 1.0, <https://docs.ambientcg.com/license/>',
         '- Poly Haven: <https://polyhaven.com> — CC0 1.0, <https://polyhaven.com/license>',
         '- "procedural": generated by this project\'s scripts (`tools/materials/gen_textures.py`, '
         '`interiors_blender.py`) and released as CC0 1.0.', '',
         '| material | files | source | author | licence |', '|---|---|---|---|---|']
    for e in man['materials']:
        s = e['source']
        L.append(f"| `{e['name']}` | `{e['category']}/{e['name']}_*.webp` | [{s['site']} {s['id']}]({s['url']}) | {s['author']} | {s['license']} |")
    L += ['', '## Window interiors atlas', '',
          '`glass/interiors_atlas.webp`, `glass/interiors_atlas_small.webp`: rooms modelled and rendered procedurally with '
          'Blender Cycles by `tools/materials/interiors_blender.py` (no external assets). CC0 1.0.', '',
          '## Environment map', '',
          f"`env/{env['file']}`: [{env['source']['site']} {env['source']['id']}]({env['source']['url']}) by "
          f"{env['source']['author']}, {env['source']['license']}. Processing: {env['processing']}.", '']
    open(os.path.join(TEX, 'CREDITS.md'), 'w').write('\n'.join(L))


def props():
    man = json.load(open(os.path.join(PROPS, 'props.json')))
    L = ['# Prop model credits', '',
         'Every file in `public/models/props/` is **CC0 1.0 (public domain dedication)**.', '',
         '- Poly Haven models: <https://polyhaven.com/models>, CC0 1.0 (<https://polyhaven.com/license>). The scans were '
         'trimmed to one variant, re-centred, decimated (meshoptimizer), their textures resized to WebP, and '
         'meshopt-compressed by `tools/materials/props_blender.py` + `optimize_props.cjs`.',
         '- "procedural": modelled from primitives by `tools/materials/props_blender.py` for this project, CC0 1.0.', '',
         '| prop | files | source | author | licence |', '|---|---|---|---|---|']
    for p in man['props']:
        s = p['source']
        src = f"[{s['site']} {s['id']}]({s['url']})" if s['site'] != 'procedural' else 'procedural (`props_blender.py`)'
        L.append(f"| `{p['name']}` | `{p['file']}`, `{p['lod1']}` | {src} | {s['author']} | {s['license']} |")
    L.append('')
    open(os.path.join(PROPS, 'CREDITS.md'), 'w').write('\n'.join(L))


if __name__ == '__main__':
    textures()
    props()
    print('credits written')
