# NPC variant definitions for Harare CBD street life. Colours are picked from
# src/data/streetlife.js PEDESTRIAN_STYLES (skinTones, hair, shirt, trousers, skirt, dress, zambiaWrap,
# headwrap, suit, suitShirt, tie, shoes, hats, uniforms).
#
# garment rule forms (see build_npcs.py):
#   ('keep',)                          original texture
#   ('tint', hex[, flat])              recolour keeping shading detail (flat=True blurs prints/logos away)
#   ('classes', [hex...])              k-means the texture into len(list) colour classes (sorted dark->light)
#                                      and recolour each class
#   ('split', zfrac, ruleAbove, ruleBelow)   by height (fraction of body height)
#   ('pattern', kind, [hex...])        procedural print on the garment UVs: wax | check | stripe | dots
#
# phenotype values are MakeHuman macros (0..1): age 0.1875 ~ 11 y, 0.5 = 25 y, 1.0 = 90 y.

# Stacking order of the garments (higher = worn further out). MakeHuman's own z_depth values mostly tie
# at 50, so tucked / untucked is spelled out here. build_npcs.py removes hidden inner faces and pulls any
# inner-layer vertex that pokes through an outer layer back under it (resolve_layers) using this order.
LAYER_Z = {
    # shoes sit under trouser hems and long skirts
    'shoes01': 20, 'shoes03': 20, 'shoes04': 20, 'shoes05': 20, 'toigo_flats': 20, 'toigo_ballet_flats': 20,
    'toigo_mj_cloth_shoes': 20, 'culturalibre_sneakers': 20,
    # tucked tops go under the bottoms
    'toigo_basic_tucked_t-shirt': 40, 'elvs_male_shirt_tie_tucked1': 40,
    # bottoms
    'elvs_male_trouser': 50, 'punkduck_male_classic_jeans': 50, 'punkduck_female_tight_jeans': 50,
    'toigo_wool_pants': 50, 'cortu_jeans_shorts': 50, 'elvs_pencil_skirt': 50, 'elvs_gored_midi_skirt': 50,
    'toigo_long_full_skirt': 50,
    # untucked tops hang over the bottoms
    'elvs_crude_t-shirt_male': 55, 'joepal_crude_t-shirt_female': 55, 'namuhekam_male_polo_shirt': 55,
    'punkduck_v_neck_top': 55, 'elvs_male_shirt_untucked_bd1': 55,
    # hair meshes fall over collars; outer layers; hats on top
    '__hair__': 58,
    'janexx_old_female_sweater': 60, 'elvs_hooded_sweat_jacket1': 61, 'elvs_ladies_apron': 65,
    'toigo_maga_hat': 70, 'mindfront_patrol_cap': 70, 'jujube_newsboy_cap': 70,
    '__headwrap__': 72,
}

SKIN = ['#3b2219', '#4a2c20', '#5a3825', '#6b4430', '#7a5038', '#8d5f42', '#a0714f']

VARIANTS = [
    # ---------------------------------------------------------------- men
    dict(id='man_business_suit', gender='male', roles=['office_man', 'street_preacher'],
         desc='Office worker in a charcoal two-piece suit, white shirt and maroon tie',
         phenotype=dict(gender=1.0, age=0.45, muscle=0.5, weight=0.55, height=0.55, proportions=0.6),
         skin=('middleage_african_male', SKIN[1]), hair=('crop', '#0e0b0a'),
         clothes=[('toigo_male_suit_tie_and_jacket', ('classes', ['#22262e', '#6b1f2a', '#f4f1e8'])),
                  ('shoes04', ('tint', '#111111'))]),
    dict(id='man_shirt_tie', gender='male', roles=['office_man'],
         desc='Clerk in light blue shirt, navy tie and grey trousers',
         phenotype=dict(gender=1.0, age=0.38, muscle=0.45, weight=0.45, height=0.5, proportions=0.55),
         skin=('young_african_male', SKIN[2]), hair=('crop', '#1a1412'),
         clothes=[('elvs_male_shirt_tie_tucked1', ('tie', '#bcd4ec', '#1e2d55')),
                  ('elvs_male_trouser', ('tint', '#3b3b3b')),
                  ('shoes01', ('tint', '#3b2a1e'))]),
    dict(id='man_tshirt_jeans_cap', gender='male', roles=['casual_man', 'youth'],
         desc='Young man in red t-shirt, jeans and black baseball cap',
         phenotype=dict(gender=1.0, age=0.33, muscle=0.6, weight=0.45, height=0.58, proportions=0.6),
         skin=('young_african_male', SKIN[0]), hair=('crop', '#0e0b0a'),
         clothes=[('elvs_crude_t-shirt_male', ('tint', '#b01e23', True)),
                  ('punkduck_male_classic_jeans', ('tint', '#27354f')),
                  ('toigo_maga_hat', ('tint', '#111111', True)),
                  ('shoes05', ('keep',))]),
    dict(id='man_polo_chinos', gender='male', roles=['casual_man'],
         desc='Man in yellow polo shirt, khaki chinos and brown shoes',
         phenotype=dict(gender=1.0, age=0.5, muscle=0.4, weight=0.7, height=0.45, proportions=0.5),
         skin=('middleage_african_male', SKIN[3]), hair=('crop', '#1a1412'),
         clothes=[('namuhekam_male_polo_shirt', ('tint', '#f2c200', True)),
                  ('toigo_wool_pants', ('tint', '#c2b28f')),
                  ('shoes01', ('keep',))]),
    dict(id='man_overalls', gender='male', roles=['handcart_pusher', 'worker', 'car_washer'],
         desc='Worker in navy overalls over a grey t-shirt, work boots',
         phenotype=dict(gender=1.0, age=0.4, muscle=0.8, weight=0.5, height=0.52, proportions=0.5),
         skin=('young_african_male', SKIN[1]), hair=('shaved', '#0e0b0a'),
         clothes=[('male_worksuit01', ('classes', ['#1e2d55', '#7c8187'])),
                  ('shoes03', ('tint', '#2a2320'))]),
    dict(id='man_hoodie', gender='male', roles=['youth', 'hwindi'],
         desc='Youth / kombi tout in grey hooded sweat jacket, dark jeans and white sneakers',
         phenotype=dict(gender=1.0, age=0.28, muscle=0.55, weight=0.4, height=0.6, proportions=0.6),
         skin=('young_african_male', SKIN[2]), hair=('crop', '#0e0b0a'),
         clothes=[('elvs_hooded_sweat_jacket1', ('tint', '#5c5752', True)),
                  ('punkduck_male_classic_jeans', ('tint', '#1f2a44')),
                  ('culturalibre_sneakers', ('tint', '#ffffff', True))]),
    dict(id='man_elder_flatcap', gender='male', roles=['elder'],
         desc='Elderly man in brown jacket, grey trousers and flat cap, grey stubble',
         phenotype=dict(gender=1.0, age=0.9, muscle=0.3, weight=0.5, height=0.42, proportions=0.4),
         skin=('old_african_male', SKIN[2]), hair=('crop', '#5c5752'), beard=('stubble', '#b8b4ae'),
         clothes=[('male_casualsuit05', ('split', 0.53, ('tint', '#6b4a2e', True), ('tint', '#6f7378'))),
                  ('jujube_newsboy_cap', ('tint', '#3b3b3b', True)),
                  ('shoes01', ('tint', '#3b2a1e'))]),
    dict(id='man_security_guard', gender='male', roles=['security_guard'],
         desc='Private security guard: blue-grey shirt, navy trousers, navy patrol cap, boots',
         phenotype=dict(gender=1.0, age=0.42, muscle=0.6, weight=0.6, height=0.55, proportions=0.5),
         skin=('middleage_african_male', SKIN[1]), hair=('shaved', '#0e0b0a'),
         clothes=[('elvs_male_shirt_untucked_bd1', ('tint', '#6f7c8f', True)),
                  ('elvs_male_trouser', ('tint', '#1e2d55')),
                  ('mindfront_patrol_cap', ('tint', '#1e2d55', True)),
                  ('shoes03', ('tint', '#111111'))]),
    dict(id='man_police_zrp', gender='male', roles=['police'],
         desc='ZRP police officer: light blue-grey shirt, navy trousers and cap, black boots',
         phenotype=dict(gender=1.0, age=0.4, muscle=0.65, weight=0.55, height=0.6, proportions=0.6),
         skin=('young_african_male', SKIN[3]), hair=('shaved', '#0e0b0a'),
         clothes=[('elvs_male_shirt_untucked_bd1', ('tint', '#9fb3c8', True)),
                  ('elvs_male_trouser', ('tint', '#1e2d55')),
                  ('mindfront_patrol_cap', ('tint', '#1e2d55', True)),
                  ('shoes03', ('tint', '#111111'))]),
    dict(id='man_apostolic', gender='male', roles=['apostolic'],
         desc='Apostolic church member: white knee-length robe, shaved head, full beard, barefoot',
         phenotype=dict(gender=1.0, age=0.6, muscle=0.5, weight=0.5, height=0.55, proportions=0.5),
         skin=('middleage_african_male', SKIN[1]), hair=('bald', None), beard=('full', '#141010'),
         clothes=[('wdg_mycenaean_tunic', ('tint', '#f8f8f4', True))]),
    dict(id='boy_primary_school', gender='male', roles=['school_kid'],
         desc='Primary school boy: short-sleeved khaki shirt, khaki shorts to above the knee, brown socks, black shoes',
         phenotype=dict(gender=1.0, age=0.17, muscle=0.5, weight=0.45, height=0.5, proportions=0.5),
         skin=('young_african_male', SKIN[2]), hair=('crop', '#0e0b0a'), socks=('#8b6f47', 0.17),
         # school uniform cut from full garments: sleeves end mid upper arm, trouser legs just above the knee
         cut={'elvs_male_shirt_untucked_bd1': dict(upperarm=0.5), 'elvs_male_trouser': dict(thigh=0.72)},
         clothes=[('elvs_male_shirt_untucked_bd1', ('tint', '#c9b27c', True)),
                  ('elvs_male_trouser', ('tint', '#a08a5c', True)),
                  ('shoes04', ('tint', '#111111'))]),
    dict(id='boy_high_school', gender='male', roles=['school_kid'],
         desc='High school boy: white shirt, maroon tie, grey trousers, black shoes',
         phenotype=dict(gender=1.0, age=0.3, muscle=0.45, weight=0.4, height=0.6, proportions=0.5),
         skin=('young_african_male', SKIN[1]), hair=('crop', '#0e0b0a'),
         clothes=[('elvs_male_shirt_tie_tucked1', ('tie', '#ffffff', '#6b1f2a')),
                  ('elvs_male_trouser', ('tint', '#6f7378')),
                  ('shoes04', ('tint', '#111111'))]),
    # ---------------------------------------------------------------- women
    dict(id='woman_office_suit', gender='female', roles=['office_woman'],
         desc='Office worker in a navy skirt suit, black flats, relaxed bob',
         phenotype=dict(gender=0.0, age=0.4, muscle=0.4, weight=0.55, height=0.5, proportions=0.6, cupsize=0.5),
         skin=('middleage_african_female', SKIN[2]), hair=('bob02', '#1a1412'),
         clothes=[('toigo_female_suit', ('classes', ['#1e2d55', '#f4f1e8'])),
                  ('toigo_flats', ('tint', '#111111'))]),
    dict(id='woman_dress_bright', gender='female', roles=['casual_woman'],
         desc='Woman in a bright blue knee-length shift dress, braids / cornrows',
         phenotype=dict(gender=0.0, age=0.33, muscle=0.4, weight=0.5, height=0.48, proportions=0.6, cupsize=0.55),
         skin=('young_african_female', SKIN[1]), hair=('cornrows', '#0e0b0a'),
         clothes=[('toigo_shift_dress', ('tint', '#1d4fb8', True)),
                  ('toigo_ballet_flats', ('tint', '#111111'))]),
    dict(id='woman_blouse_skirt', gender='female', roles=['casual_woman', 'office_woman'],
         desc='Woman in a cream tucked top and black pencil skirt with a red dhuku (head wrap)',
         phenotype=dict(gender=0.0, age=0.45, muscle=0.35, weight=0.7, height=0.45, proportions=0.5, cupsize=0.6),
         skin=('middleage_african_female', SKIN[3]), hair=('none', None), headwrap=('solid', ['#d62f3a']),
         clothes=[('toigo_basic_tucked_t-shirt', ('tint', '#f2efe6', True)),
                  ('elvs_pencil_skirt', ('tint', '#111111')),
                  ('toigo_flats', ('tint', '#3b2a1e'))]),
    dict(id='woman_zambia_wrap', gender='female', roles=['market_woman', 'vendor'],
         desc='Market woman in a zambia wrap cloth (wax print) over a t-shirt, yellow-print dhuku',
         phenotype=dict(gender=0.0, age=0.5, muscle=0.45, weight=0.8, height=0.45, proportions=0.4, cupsize=0.7),
         skin=('middleage_african_female', SKIN[1]), hair=('none', None), headwrap=('wax', ['#f2c200', '#1d4fb8', '#ffffff']),
         clothes=[('joepal_crude_t-shirt_female', ('tint', '#2e8b57', True)),
                  ('toigo_long_full_skirt', ('pattern', 'wax', ['#d62f3a', '#f2c200', '#111111'])),
                  ('toigo_mj_cloth_shoes', ('tint', '#3b2a1e'))]),
    dict(id='woman_vendor_apron', gender='female', roles=['vendor', 'market_woman'],
         desc='Street vendor: orange t-shirt, wax-print wrap skirt, blue gingham apron, orange-print dhuku',
         phenotype=dict(gender=0.0, age=0.42, muscle=0.5, weight=0.75, height=0.48, proportions=0.45, cupsize=0.65),
         skin=('young_african_female', SKIN[2]), hair=('none', None), headwrap=('wax', ['#ff7f2a', '#6b1f2a', '#ffffff']),
         clothes=[('joepal_crude_t-shirt_female', ('tint', '#ff7f2a', True)),
                  ('toigo_long_full_skirt', ('pattern', 'wax', ['#1d4fb8', '#ffffff', '#f2c200'])),
                  ('elvs_ladies_apron', ('pattern', 'check', ['#1d4fb8', '#f2efe6'])),
                  ('toigo_flats', ('tint', '#3b2a1e'))]),
    dict(id='woman_elder', gender='female', roles=['elder'],
         desc='Elderly woman in a cardigan, long skirt and headscarf',
         phenotype=dict(gender=0.0, age=0.88, muscle=0.3, weight=0.65, height=0.4, proportions=0.4, cupsize=0.5),
         skin=('old_african_female', SKIN[2]), hair=('none', None), headwrap=('solid', ['#1e2d55']),
         clothes=[('janexx_old_female_sweater', ('tint', '#6b1f2a', True)),
                  ('toigo_long_full_skirt', ('tint', '#3b3b3b', True)),
                  ('toigo_mj_cloth_shoes', ('tint', '#111111'))]),
    dict(id='woman_apostolic', gender='female', roles=['apostolic'],
         desc='Apostolic church member: white long dress and white headscarf, barefoot',
         phenotype=dict(gender=0.0, age=0.5, muscle=0.4, weight=0.6, height=0.46, proportions=0.5, cupsize=0.55),
         skin=('middleage_african_female', SKIN[0]), hair=('none', None), headwrap=('solid', ['#f8f8f4']),
         clothes=[('wdg_mycenaean_tunic', ('tint', '#f8f8f4', True))]),
    dict(id='girl_primary_school', gender='female', roles=['school_kid'],
         desc='Primary school girl: light blue dress, white socks, black shoes, cornrows',
         phenotype=dict(gender=0.0, age=0.16, muscle=0.5, weight=0.45, height=0.5, proportions=0.5),
         skin=('young_african_female', SKIN[2]), hair=('cornrows', '#0e0b0a'), socks=('#ffffff', 0.15),
         clothes=[('toigo_shift_dress', ('tint', '#7fb2e5', True)),
                  ('toigo_mj_cloth_shoes', ('tint', '#111111'))]),
    dict(id='girl_high_school', gender='female', roles=['school_kid'],
         desc='High school girl: white top, navy skirt, white socks, black shoes, cornrows',
         phenotype=dict(gender=0.0, age=0.3, muscle=0.45, weight=0.45, height=0.5, proportions=0.55, cupsize=0.35),
         skin=('young_african_female', SKIN[1]), hair=('cornrows', '#0e0b0a'), socks=('#ffffff', 0.2),
         clothes=[('toigo_basic_tucked_t-shirt', ('tint', '#ffffff', True)),
                  ('elvs_gored_midi_skirt', ('tint', '#1e2d55', True)),
                  ('toigo_mj_cloth_shoes', ('tint', '#111111'))]),
    dict(id='woman_jeans_top', gender='female', roles=['youth', 'casual_woman'],
         desc='Young woman in a pink top and tight jeans with an afro puff',
         phenotype=dict(gender=0.0, age=0.3, muscle=0.45, weight=0.45, height=0.55, proportions=0.7, cupsize=0.5),
         skin=('young_african_female', SKIN[4]), hair=('afro01', '#0e0b0a'),
         clothes=[('punkduck_v_neck_top', ('tint', '#e05a8a', True)),
                  ('punkduck_female_tight_jeans', ('tint', '#2e3f66')),
                  ('culturalibre_sneakers', ('tint', '#ffffff', True))]),
    dict(id='woman_casual_tee', gender='female', roles=['casual_woman'],
         desc='Woman in a teal t-shirt and black trousers, hair in a bun under a black wrap',
         phenotype=dict(gender=0.0, age=0.36, muscle=0.4, weight=0.6, height=0.52, proportions=0.5, cupsize=0.6),
         skin=('young_african_female', SKIN[3]), hair=('none', None), headwrap=('solid', ['#111111']),
         clothes=[('joepal_crude_t-shirt_female', ('tint', '#20a0b0', True)),
                  ('elvs_male_trouser', ('tint', '#111111', True)),
                  ('toigo_flats', ('tint', '#111111'))]),
]
